"""add google auth fields

Revision ID: 0df8cbbd5a71
Revises: 3f955de24075
Create Date: 2026-04-30 13:36:15.208693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df8cbbd5a71'
down_revision = '3f955de24075'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('picture')
        batch_op.drop_column('google_id')

    # with op.batch_alter_table('events', schema=None) as batch_op:
    #     batch_op.alter_column('host_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)

    # ### end Alembic commands ###
