"""replace stripe with intasend

Revision ID: 51cc647087ca
Revises: 0df8cbbd5a71
Create Date: 2026-05-04 18:16:38.086207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cc647087ca'
down_revision = '0df8cbbd5a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_events')
    with op.batch_alter_table('events', schema=None) as batch_op:
        pass

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intasend_invoice_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_payments_intasend_invoice_id', ['intasend_invoice_id'])
        batch_op.drop_column('stripe_payment_intent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('uq_payments_intasend_invoice_id', type_='unique')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('intasend_invoice_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        pass

    op.create_table('_alembic_tmp_events',
    # ... rest of your columns
    )
    # ### end Alembic commands ###