"""empty message

Revision ID: 542032a2fd7c
Revises: 51cc647087ca
Create Date: 2026-05-04 19:50:05.591673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542032a2fd7c'
down_revision = '51cc647087ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table('notifications'):
        op.create_table('notifications',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('message', sa.String(length=500), nullable=False),
            sa.Column('data', sa.Text(), nullable=True),
            sa.Column('is_read', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # NOTE: skipping altering `events.host_id` nullability to avoid failing
    # upgrade when existing rows have NULL host_id values. If you want to
    # enforce NOT NULL, first ensure all existing events have a valid
    # `host_id` (e.g., migrate them to a default user) and then run a
    # dedicated migration that sets nullable=False.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('notifications')
    # ### end Alembic commands ###
